import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Sonner from '@/components/providers';
import Navbar from '@/components/sections/navbar';
import { Providers } from './providers';
import { auth } from '@/auth';
import SpotlightCursor from './cursor';
import CanvasCursor from './canvasCursor';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <Navbar session={session} />
            {children}
            <Sonner />
            {/* <SpotlightCursor /> */}
            <CanvasCursor />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
